### ISSUE TITLE
Melhorar o PFIv

### ISSUE THREAD

**Issue by sHilgert** [parahyba-valley/parahyba-valley-web#10]
fazer o pvIf não quebrar caso um subitem não exista, ex: pvIf="bla.ble.bli", caso ble não exista ele quebra pq tenta acessar o bli

**Comment by RafaelSNascimento** [comment]
Eu acho esse comportamento correto. Vamos ficar passivos a bug se escondermos o erro causado por acesso a propriedade de undefined. Se necessário coloque um PVif antes. Na real, poderiamos melhorar o PVif para aceitar bla.ble && bla.ble.bli, por exemplo. Mas ai entra como refinamento do PVIf e não bug

**Comment by sHilgert** [comment]
Boa, vamos colocar uma feature no PVIf para dar suporte a && e || então

**Comment by vitebo** [comment]
eu vou tentar trabalhar nisso

**Comment by vitebo** [comment]
gente eu to com dificuldade pra fazer o setup do projeto, vocês conseguem me ajudar?
eu to documentando os meus passos aqui e vou aproveitar pra incrementar o README depois.
o que eu fiz até agora foi:
- pull do projeto + yarn install como consta na doc
- depois eu criei uma conta no [fauna](https://fauna.com/)
- criei um db e uma secret key la no fauna
- coloquei no arquivo arquivo `./envs/app.env` as credenciais pra autenticar no fauna

Nesse ponto eu ja to conseguindo bater la no fauna, o problema é que eu não sei quais collections e indexes eu preciso criar la, como a minha base ta vazia, eu fico tomando esse erro ao tentar carregar os dados do slider:

![image](https://user-images.githubusercontent.com/19560693/107104878-68a81000-6802-11eb-9d83-c8dbaddc93c6.png)

existe alguma espécie de bumb ja populado que eu consiga utilizar?
