### ISSUE TITLE
PVFor está com bug quando feito em cascata

### ISSUE THREAD

**Issue by sHilgert** [parahyba-valley/parahyba-valley-web#2]
Peguei um problema ao usar um PVFor dentro de outro PVFor, iterando na variável usada como escopo do primeiro for.
Exemplo:
```html
<div class="slider__slides__item" pvFor="slide in slides">
  <div pvFor="tag in slide.tags"> <!-- Esse for não funciona --/>
  </div>
</div>
```

**Comment by RafaelSNascimento** [comment]
[Esta issue foi resolvida neste commit.](https://github.com/parahyba-valley/parahyba-valley-web/commit/ad4641d84b1f5c9f329247d18fa811b46edbc3db)
